[package]
name = "rust-gcd"
version = "0.1.0"
authors = ["Serkan Özel <srknzl.github@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.3.2"
serde = {version = "1.0.127", features = ["derive"]}